name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push to gh-pages branch
      pages: write # To deploy to GitHub Pages (if using GitHub Pages action)
      id-token: write # To authenticate with GitHub Pages (if using GitHub Pages action)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or the version specified in your frontend/package.json engines field
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build for GitHub Pages
        working-directory: ./frontend
        # The base URL should be the repository name for GitHub Pages
        # e.g., /my-repo-name/
        # GITHUB_REPOSITORY is in the format owner/repository-name
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "VITE_BASE_URL=/$REPO_NAME/" > .env.production
          npm run build
        env:
          # VITE_BASE_URL will be set in the run step above
          CI: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          # Optional: if your site is in a subdirectory of the gh-pages branch
          # publish_branch: gh-pages # Default is gh-pages
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: Automated deployment to GitHub Pages
          # allow_empty_commit: false
          # force_orphan: false
          # cname: example.com # If you have a custom domain
```
